# Question 2

In [105]:
import numpy as np
m= np.random.randint(0, 10, size=(3,3))
print(m)
print(m.mean(axis = 0))
print(m.max(axis = 0))
print(m.min(axis = 0))

[[0 4 4]
 [0 0 7]
 [1 3 6]]
[ 0.33333333  2.33333333  5.66666667]
[1 4 7]
[0 0 4]


# Question 3

In [15]:
n= np.random.randint(-100, 100, size=(3,3))
print(n)
print(n.mean(axis = 0))
print(n.max(axis = 0))
print(n.min(axis = 0))

[[ 24 -79 -34]
 [-41  78 -45]
 [ 79  89  33]]
[ 20.66666667  29.33333333 -15.33333333]
[79 89 33]
[-41 -79 -45]


In [17]:
p= np.random.randint(-10, 10, size=(2,2))
print(p)

[[ 7 -5]
 [-1  8]]


# Question 4

Write a python script to randomly generate a 2D array 10 x 8 of float values on interval [-10, 10].

And then, get a float number from user and find its closest values in the array.
SOME GUIDES: 
i) use argmin() function for your problem: https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html;
Or reshape to 1D, subtract array to value and sort. 
Optional: If you passed the above problem, extend it to find 3 closest values in the array.


In [26]:
ab= np.random.randint(-10.0,10.0, size=(10, 8))
ab

array([[  9,   2,  -4,  -5,  -2,   2,  -3,  -2],
       [ -9,   6,  -5,   0,   3,   7,   8,   1],
       [ -8,   3,   7,   0,   6,  -9,  -1,  -2],
       [  8,  -4,  -5,  -3,   1,  -9,   2,   0],
       [  1, -10,  -2,  -4,   1,  -4,   3,   8],
       [ -1,   3,  -2,   1,  -6,  -7, -10,  -9],
       [  6,  -9,  -3,   6,  -8,   1,   8,  -9],
       [ -6,  -3,  -1,   4,   1,   2,   0,  -1],
       [ -3,  -3,   0,  -3,  -2,   8,  -6,  -3],
       [ -8,   5,  -2,   1,   2,  -5,  -7,   0]])

In [27]:
ab.reshape(1,80)


array([[  9,   2,  -4,  -5,  -2,   2,  -3,  -2,  -9,   6,  -5,   0,   3,
          7,   8,   1,  -8,   3,   7,   0,   6,  -9,  -1,  -2,   8,  -4,
         -5,  -3,   1,  -9,   2,   0,   1, -10,  -2,  -4,   1,  -4,   3,
          8,  -1,   3,  -2,   1,  -6,  -7, -10,  -9,   6,  -9,  -3,   6,
         -8,   1,   8,  -9,  -6,  -3,  -1,   4,   1,   2,   0,  -1,  -3,
         -3,   0,  -3,  -2,   8,  -6,  -3,  -8,   5,  -2,   1,   2,  -5,
         -7,   0]])

In [31]:
ab1 = ab.sort()
print(ab1)

None


# Question5
Read the following financial function to more understand about numpy: https://docs.scipy.org/doc/numpy/reference/routines.financial.html. For each function, give a example and try it.


#Compute the future value.
numpy.fv(rate, nper, pmt, pv, when='end')

In [37]:
#Examples

#What is the future value after 10 years of saving $100 now, with an additional monthly savings of $100. 
#Assume the interest rate is 5% (annually) compounded monthly?
np.fv(0.05/12, 10*12, -100, -100)

15692.928894335748

#ADDITIONAL PART

Download iris data set from here https://archive.ics.uci.edu/ml/datasets/iris, and save it to a file.
Load data of the downloaded file into a 2D array of numbers where 3 types of flowers is mapped to vector (1 = Setosa, 2=Versicolour, 3=Virginica). 
GUIDE: use loadtxt() or genfromtxt() to load file content into a list of tuple, then run for loop to convert list of tuple to 1D array, then reshape it to 2D. While converting, map name of flower to number.   
Calculate 3 covariance matrix of sepal length and sepal width for each type of flower. (see: https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html )


In [110]:
import csv
import pandas as pd
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [111]:
iris.head(10)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa
8  4.9  3.1  1.5  0.1  Iris-setosa
9  5.4  3.7  1.5  0.2  Iris-setosa

In [94]:
row_0 = iris.iloc[0]
row_0

5.1                    4.9
3.5                      3
1.4                    1.4
0.2                    0.2
Iris-setosa    Iris-setosa
Name: 0, dtype: object

In [95]:
row_0.index

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [97]:
iris.shape

(149, 5)